<?php
/**
 * SimpleMedia.
 *
 * @copyright Axel Guckelsberger
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package SimpleMedia
 * @author Axel Guckelsberger <info@guite.de>.
 * @link http://zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.5.4 (http://modulestudio.de) at Mon Nov 28 12:34:51 CET 2011.
 */

/**
 * This is the Ajax api helper class.
 */
class SimpleMedia_Api_Base_Ajax extends Zikula_AbstractApi
{
    /**
     * get available Ajax panel links
     *
     * @return array Array of admin links
     */
    public function getlinks()
    {
        $links = array();

        return $links;
    }
}
