<?php
/**
 * SimpleMedia.
 *
 * @copyright Axel Guckelsberger
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package SimpleMedia
 * @author Axel Guckelsberger <info@guite.de>.
 * @link http://zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.5.4 (http://modulestudio.de) at Mon Nov 28 12:34:51 CET 2011.
 */


/**
 * This is the Ajax controller class providing navigation and interaction functionality.
 */
class SimpleMedia_Controller_Ajax extends SimpleMedia_Controller_Base_Ajax
{
    /**
     * Retrieve item list for selection in Forms and Content type plugin
     */
    public function getFileList($args)
    {
        $objectType = 'medium';
        $entityClass = 'SimpleMedia_Entity_' . ucfirst($objectType);
        $repository = $this->entityManager->getRepository($entityClass);

        $catid = (int) (isset($args['catid'])) ? $args['catid'] : $this->request->getPost()->filter('catid', null, FILTER_VALIDATE_INT);

        $sort = (isset($args['sort']) && !empty($args['sort'])) ? $args['sort'] : $this->request->getPost()->filter('sort', '', FILTER_SANITIZE_STRING);
        if (empty($sort) || !in_array($sort, $repository->getAllowedSortingFields())) {
            $sort = $repository->getDefaultSortingField();
        }

        $sdir = (isset($args['sortdir']) && !empty($args['sortdir'])) ? $args['sortdir'] : $this->request->getPost()->filter('sortdir', '', FILTER_SANITIZE_STRING);
        $sdir = strtolower($sdir);
        if ($sdir != 'asc' && $sdir != 'desc') {
            $sdir = 'asc';
        }

        $keyword = (isset($args['keyword'])) ? $args['keyword'] : $this->request->getPost()->filter('keyword', '', FILTER_SANITIZE_STRING);

        $thumbnr = (isset($args['thumbnr'])) ? $args['thumbnr'] : FormUtil::getPassedValue('thumbnr', 0, 'POST');
        if ($thumbnr != 'original') {
            $thumbnr = (int) $thumbnr;
        }
        if ($thumbnr == 0 || ($thumbnr != 'original' && !is_numeric($thumbnr))) {
            $thumbnr = $this->getVar('defaultThumbNumber', 1);
        }

        $where = '';
        if ($catid > 0) {
            /** TODO */
        }
        /** done in repository (using getpost) if (!empty($keyword)) {
            $where .= (!empty($where)) ? ' AND ' : '';
            $where .= '(tbl.title LIKE \'%' . DataUtil::formatForStore($keyword) . '%\' OR tbl.description LIKE \'%' . DataUtil::formatForStore($keyword) . '%\')';
        }*/
        $sortParam = $sort . ' ' . $sdir;

        $objectData = $repository->selectWhere($where, $sortParam);

        $slimFiles = array();
        foreach ($objectData as $medium) {
            $slimFiles[] = $this->prepareSlimFile($medium, $thumbnr);
        }

        return new Zikula_Response_Ajax($slimFiles);
    }

    private function prepareSlimFile($medium, $thumbnr)
    {
        $smView = Zikula_View::getInstance('SimpleMedia', false);
        $smView->assign('medium', $medium)
               ->assign('thumbnr', $thumbnr);

        return array('id'           => $medium['id'],
                     'title'        => str_replace('&amp;', '&', $medium['title']),
                     'description'  => $medium['description'],
                     'extension'    => $medium['theFileMeta']['extension'],
                     'previewInfo'  => base64_encode($smView->fetch('external/fileInfo.tpl')));
    }
}
