<?php
/**
 * SimpleMedia.
 *
 * @copyright Axel Guckelsberger
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package SimpleMedia
 * @author Axel Guckelsberger <info@guite.de>.
 * @link http://zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.5.4 (http://modulestudio.de) at Mon Nov 28 12:34:51 CET 2011.
 */

/**
 * Generic item list content plugin implementation class
 */
class SimpleMedia_ContentType_ItemList extends SimpleMedia_ContentType_Base_ItemList
{
    private $catid;

    public function loadData(&$data)
    {
        parent::loadData($data);

        $this->catid = $data['catid'];
        if ($data['catid'] !== null && $data['catid'] > 0) {
            $_GET['catid'] = $data['catid'];
        }
    }

    public function getDefaultData()
    {
        return array('objectType' => 'medium',
                     'sorting' => 'default',
                     'amount' => 10,
                     'template' => 'itemlist_display_gallery.tpl',
                     'filter' => '',
                     'catid' => null);
    }
}

function SimpleMedia_Api_ContentTypes_itemlist($args)
{
    return new SimpleMedia_Api_ContentTypes_itemListPlugin();
}
