<?php
/**
 * SimpleMedia.
 *
 * @copyright Axel Guckelsberger
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package SimpleMedia
 * @author Axel Guckelsberger <info@guite.de>.
 * @link http://zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.5.4 (http://modulestudio.de) at Mon Nov 28 12:34:51 CET 2011.
 */


/**
 * Validator class for encapsulating entity validation methods.
 *
 * This is the concrete validation class for medium entities.
 */
class SimpleMedia_Entity_Validator_Medium extends SimpleMedia_Entity_Validator_Base_Medium
{
    // here you can add custom validation methods or override existing checks
}
