<?php
/**
 * SimpleMedia.
 *
 * @copyright Axel Guckelsberger
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package SimpleMedia
 * @author Axel Guckelsberger <info@guite.de>.
 * @link http://zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.5.3 (http://modulestudio.de) at Mon Oct 10 12:08:55 CEST 2011.
 */

/**
 * @param array   $params    All attributes passed to this function from the template
 * @param object  &$smarty   Reference to the Smarty object
 * @param array   $file      Given file array
 * @param boolean $blockcall Optional - if true the plugin was called from a block (for ensuring unique id attributes) 
 * @param int     $thumbnr   Thumbnail number: 1..x (optional, default to modvar setting)
 * @return string according template output
 */
function smarty_function_getinlinesnippet($params, &$smarty) 
{
    if (!isset($params['medium'])) {
        $smarty->trigger_error("smarty_function_getinlinesnippet: missing parameter 'medium'");
        return false;
    }

    if (!isset($params['blockcall']) || !is_bool($params['blockcall'])) {
        $params['blockcall'] = false;
    }

    if (!isset($params['externalPreview']) || ($params['externalPreview'] != 0 && $params['externalPreview'] != 1)) {
        $params['externalPreview'] = 0;
    }

    $thumbnr = (isset($params['thumbnr']) && (is_numeric($params['thumbnr']) || $params['thumbnr'] == 'original')) ? $params['thumbnr'] : (int) FormUtil::getPassedValue('thumbnr', 0, 'GETPOST');
    if ($thumbnr != 'original' && $thumbnr == 0) {
        $thumbnr = ModUtil::getVar('SimpleMedia', 'defaultThumbNumber', 1);
    }
    if ($thumbnr == 'original' && FormUtil::getPassedValue('type', 'user', 'GETPOST') == 'admin'
                               && FormUtil::getPassedValue('func', 'main', 'GETPOST') == 'view') {
        $thumbnr = ModUtil::getVar('SimpleMedia', 'defaultThumbNumber', 1);
    }

    if (!isset($params['zoomMode'])) {
        $params['zoomMode'] = 'nozoom';
    }

    $res = false;

    $mimeHelper = new SimpleMedia_Util_Mime();
    $mimeType = '';
    $snippetName = '';//$mimeHelper->getInlineSnippetName($params['file']['mimetype']);
    if (!$snippetName) {
        $mimeType = $mimeHelper->guessMimetypeFromExtension($params['medium']['theFileMeta']['extension']);
        $snippetName = $mimeHelper->getInlineSnippetName($mimeType);
    }
    if (!$snippetName) {
        $snippetName = 'unknown';
    }

    $view = Zikula_View::getInstance('SimpleMedia', false);

    $view->assign('medium', $params['medium'])
         ->assign('idprefix', ($params['blockcall']) ? 'block' : '')
         ->assign('externalPreview', $params['externalPreview'])
         ->assign('mimeType', $mimeType)
         ->assign('thumbnr', $thumbnr)
         ->assign('zoomMode', $params['zoomMode']);

    $res = $view->fetch('inline/' . $snippetName . '.tpl');

    if (isset($params['assign'])) {
        $smarty->assign($params['assign'], $res);
    } else {
        return $res;
    }
}
