<?php
/**
 * SimpleMedia.
 *
 * @copyright Axel Guckelsberger
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package SimpleMedia
 * @author Axel Guckelsberger <info@guite.de>.
 * @link http://zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.5.4 (http://modulestudio.de) at Mon Nov 28 12:34:51 CET 2011.
 */

/**
 * This handler class handles the page events of the Form called by the SimpleMedia_admin_edit() function.
 * It collects common functionality required by different object types.
 */
class SimpleMedia_Form_Handler_Admin_Edit extends SimpleMedia_Form_Handler_Admin_Base_Edit
{
    // feel free to extend the base handler class here
}
