<?php
/**
 * SimpleMedia.
 *
 * @copyright Axel Guckelsberger
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package SimpleMedia
 * @author Axel Guckelsberger <info@guite.de>.
 * @link http://zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.5.3 (http://modulestudio.de) at Sun Oct 30 11:20:55 CET 2011.
 */

/**
 * This is the category api helper class.
 */
class SimpleMedia_Api_Category extends Zikula_AbstractApi
{
    /**
     * retrieves the main/default category of SimpleMedia
     *
     * @return mixed    category array on success, false on failure
     */
    public function getMainCat()
    {
        return CategoryRegistryUtil::getRegisteredModuleCategory('SimpleMedia', 'Medium', 'Main', 32); // 32 == /__System/Modules/Global
    }
}
