<?php
/**
 * SimpleMedia.
 *
 * @copyright Axel Guckelsberger
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package SimpleMedia
 * @author Axel Guckelsberger <info@guite.de>.
 * @link http://zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.5.4 (http://modulestudio.de) at Mon Nov 28 12:34:51 CET 2011.
 */

/**
 * Installer implementation class
 */
class SimpleMedia_Installer extends SimpleMedia_Base_Installer
{
    /**
     * Install the SimpleMedia application.
     *
     * @return boolean True on success, or false.
     */
    public function install()
    {
        $result = parent::install();

        $thumbDimensions = array();
        $thumbDimensions[] = array('width' => 80, 'height' => 60);
        $thumbDimensions[] = array('width' => 150, 'height' => 113);
        $thumbDimensions[] = array('width' => 200, 'height' => 150);

        $this->setVar('thumbDimensions', $thumbDimensions);

        return $result;
    }
}
