<?php
/**
 * SimpleMedia.
 *
 * @copyright Axel Guckelsberger
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package SimpleMedia
 * @author Axel Guckelsberger <info@guite.de>.
 * @link http://zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.5.4 (http://modulestudio.de) at Mon Nov 28 12:34:51 CET 2011.
 */


/**
 * Module bootstrap called when module is first initialised at runtime.
 *
 * This is only called once, and only if the core has reason to initialise this module, usually
 * to dispatch a controller request or API.
 *
 * For example you can register additional AutoLoaders with ZLoader::addAutoloader($namespace, $path)
 * whereby $namespace is the first part of the PEAR class name
 * and $path is the path to the containing folder.
 */
// initialise doctrine extension listeners
$helper = ServiceUtil::getService('doctrine_extensions');
$helper->getListener('sluggable');
$helper->getListener('timestampable');
$helper->getListener('standardfields');

define('SIMPLEMEDIA_CROPPINGMODE_ENFORCED_SIZE_ENFORCED_PROPORTIONS', 1);
define('SIMPLEMEDIA_CROPPINGMODE_VARIABLE_SIZE_ENFORCED_PROPORTIONS', 2);
define('SIMPLEMEDIA_CROPPINGMODE_VARIABLE_SIZE_VARIABLE_PROPORTIONS', 3);
