<?php
/**
 * SimpleMedia.
 *
 * @copyright Axel Guckelsberger
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package SimpleMedia
 * @author Axel Guckelsberger <info@guite.de>.
 * @link http://zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.5.4 (http://modulestudio.de) at Mon Nov 28 12:34:51 CET 2011.
 */


use Doctrine\ORM\Mapping as ORM;

/**

 * Entity extension domain class storing medium meta data.
 *
 * This is the base meta data class for medium entities.
 */
class SimpleMedia_Entity_Base_MediumMetaData extends Zikula_Doctrine2_Entity_EntityMetadata
{
    /**
     * @ORM\OneToOne(targetEntity="SimpleMedia_Entity_Medium", inversedBy="metadata")
     * @ORM\JoinColumn(name="entityId", referencedColumnName="id", unique=true)
     * @var SimpleMedia_Entity_Medium
     */
    protected $entity;

    /**
     * Get reference to owning entity.
     *
     * @return SimpleMedia_Entity_Medium
     */
    public function getEntity()
    {
        return $this->entity;
    }

    /**
     * Set reference to owning entity.
     *
     * @param SimpleMedia_Entity_Medium $entity
     */
    public function setEntity(/*SimpleMedia_Entity_Medium */$entity)
    {
        $this->entity = $entity;
    }
}
